import type { SerializedProjectAnalysis } from "../types/project.js";
import type { DetectionResult } from "../types/detection.js";

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function techRows(results: DetectionResult[]): string {
  return results
    .map(
      (r) =>
        `<tr>
  <td>${esc(r.name)}</td>
  <td>${esc(r.version ?? "-")}</td>
  <td>${r.confidence}%</td>
</tr>`
    )
    .join("\n");
}

export function toHTML(data: SerializedProjectAnalysis): string {
  const p = data.project;

  const singles: DetectionResult[] = [data.runtime, data.workspace, data.packageManager, data.language, data.api, data.testing, data.linting, data.formatting, data.deployment, data.git, data.environment, data.configFiles, data.dependencies].filter(
    (r): r is DetectionResult => r !== null && r.detected
  );
  const arrays: DetectionResult[] = [
    ...data.frameworks,
    ...data.buildTools,
    ...data.styling,
    ...data.databases,
    ...data.stateManagement,
    ...data.uiLibraries,
    ...data.auth,
  ].filter((r) => r.detected);

  const allTech = [...singles, ...arrays];

  const recs = data.recommendations
    .map(
      (r) =>
        `<li>
  <strong>[${esc(r.severity.toUpperCase())}] ${esc(r.title)}</strong>
  <p>${esc(r.description)}</p>
  <p><em>Impact:</em> ${esc(r.impact)}${r.fix ? ` &mdash; <em>Fix:</em> ${esc(r.fix)}` : ""}</p>
</li>`
    )
    .join("\n");

  const caps = data.capabilities.map((c) => `<li>${esc(c)}</li>`).join("\n");

  const m = data.metrics;
  const metrics = [
    ["Health", m.healthScore],
    ["Complexity", m.complexityScore],
    ["Maintainability", m.maintainabilityScore],
    ["Maturity", m.maturityScore],
    ["Production Readiness", m.productionReadiness],
    ["Architecture", m.architectureScore],
    ["Dependency Health", m.dependencyHealth],
    ["Testing Coverage", m.testingCoverage],
    ["Documentation", m.documentationScore],
    ["Security", m.securityScore],
    ["Performance", m.performanceScore],
  ];

  const metricRows = metrics
    .map(
      ([label, val]) =>
        `<div class="metric">
  <span class="metric-label">${label}</span>
  <div class="bar-bg"><div class="bar" style="width:${val}%"></div></div>
  <span class="metric-val">${val}</span>
</div>`
    )
    .join("\n");

  const severityColor: Record<string, string> = {
    critical: "#e74c3c",
    high: "#e67e22",
    medium: "#f1c40f",
    low: "#3498db",
    info: "#95a5a6",
  };

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${esc(p.name ?? "Project")} - Environment Report</title>
<style>
  *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
  body{font-family:system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f0f2f5;color:#1a1a2e;padding:2rem;max-width:960px;margin:0 auto;line-height:1.5}
  h1{font-size:1.8rem;margin-bottom:.25rem}
  .subtitle{color:#666;margin-bottom:1.5rem}
  .card{background:#fff;border-radius:8px;padding:1.5rem;margin-bottom:1.25rem;box-shadow:0 1px 3px rgba(0,0,0,.08)}
  .card h2{font-size:1.2rem;margin-bottom:1rem;border-bottom:2px solid #e0e0e0;padding-bottom:.5rem}
  .health-big{font-size:4rem;font-weight:700;text-align:center;padding:1rem 0}
  .health-label{text-align:center;color:#666;margin-bottom:.5rem}
  .metric{display:flex;align-items:center;margin-bottom:.5rem;gap:.75rem}
  .metric-label{width:160px;font-size:.85rem;text-align:right;flex-shrink:0}
  .bar-bg{flex:1;background:#e0e0e0;border-radius:4px;height:10px;overflow:hidden}
  .bar{height:100%;background:linear-gradient(90deg,#3498db,#2ecc71);border-radius:4px;transition:width .3s}
  .metric-val{width:36px;font-size:.85rem;font-weight:600}
  table{width:100%;border-collapse:collapse;font-size:.9rem}
  th{text-align:left;padding:.5rem .75rem;border-bottom:2px solid #ddd;background:#fafafa}
  td{padding:.5rem .75rem;border-bottom:1px solid #eee}
  tr:hover td{background:#f9f9fb}
  ul{padding-left:1.25rem}
  li{margin-bottom:.75rem}
  .severity{display:inline-block;padding:2px 8px;border-radius:4px;color:#fff;font-size:.75rem;font-weight:600;margin-right:.5rem}
</style>
</head>
<body>
<h1>${esc(p.name ?? "Unknown Project")}</h1>
<p class="subtitle">Generated by @vetwo/whichenv &mdash; ${new Date(data.timestamp).toLocaleDateString()}</p>

<div class="card">
  <div class="health-label">Overall Health Score</div>
  <div class="health-big" style="color:${m.healthScore >= 80 ? "#2ecc71" : m.healthScore >= 50 ? "#f39c12" : "#e74c3c"}">${m.healthScore}</div>
</div>

<div class="card">
  <h2>Project Details</h2>
  <p><strong>Type:</strong> ${esc(p.type)} &nbsp;|&nbsp; <strong>Version:</strong> ${esc(p.version ?? "-")} &nbsp;|&nbsp; <strong>License:</strong> ${esc(p.license ?? "-")}</p>
  ${p.description ? `<p>${esc(p.description)}</p>` : ""}
</div>

<div class="card">
  <h2>Metrics</h2>
  ${metricRows}
</div>

<div class="card">
  <h2>Detected Technologies</h2>
  <table>
    <thead><tr><th>Technology</th><th>Version</th><th>Confidence</th></tr></thead>
    <tbody>
      ${techRows(allTech)}
    </tbody>
  </table>
</div>

<div class="card">
  <h2>Recommendations</h2>
  <ul>
    ${recs || "<li>No recommendations.</li>"}
  </ul>
</div>

<div class="card">
  <h2>Capabilities</h2>
  <ul>
    ${caps || "<li>None detected.</li>"}
  </ul>
</div>
</body>
</html>`;
}
