import type { SerializedProjectAnalysis } from "../types/project.js";
import type { DetectionResult } from "../types/detection.js";

function resultRow(r: DetectionResult): string {
  return `| ${r.name} | ${r.version ?? "-"} | ${r.confidence}% |`;
}

export function toMarkdown(data: SerializedProjectAnalysis): string {
  const p = data.project;
  const lines: string[] = [];

  lines.push(`# ${p.name ?? "Unknown Project"} - Environment Report`);
  lines.push("");
  lines.push(`> Generated by @vetwo/whichenv on ${new Date(data.timestamp).toISOString()}`);
  lines.push("");

  lines.push("## Project Info");
  lines.push("");
  lines.push(`- **Name:** ${p.name ?? "unknown"}`);
  lines.push(`- **Version:** ${p.version ?? "unknown"}`);
  lines.push(`- **Description:** ${p.description ?? "-"}`);
  lines.push(`- **Type:** ${p.type}`);
  if (p.license) lines.push(`- **License:** ${p.license}`);
  if (p.author) lines.push(`- **Author:** ${p.author}`);
  lines.push("");

  const detected: DetectionResult[] = [];
  const singles: Array<{ label: string; r: DetectionResult | null }> = [
    { label: "Runtime", r: data.runtime },
    { label: "Workspace", r: data.workspace },
    { label: "Package Manager", r: data.packageManager },
    { label: "Language", r: data.language },
    { label: "API", r: data.api },
    { label: "Testing", r: data.testing },
    { label: "Linting", r: data.linting },
    { label: "Formatting", r: data.formatting },
    { label: "Deployment", r: data.deployment },
    { label: "Git", r: data.git },
    { label: "Environment", r: data.environment },
    { label: "Config Files", r: data.configFiles },
    { label: "Dependencies", r: data.dependencies },
  ];

  for (const s of singles) {
    if (s.r?.detected) detected.push(s.r);
  }
  const arrays: DetectionResult[][] = [
    data.frameworks,
    data.buildTools,
    data.styling,
    data.databases,
    data.stateManagement,
    data.uiLibraries,
    data.auth,
  ];
  for (const arr of arrays) {
    for (const r of arr) {
      if (r.detected) detected.push(r);
    }
  }

  lines.push("## Detected Technologies");
  lines.push("");
  lines.push("| Technology | Version | Confidence |");
  lines.push("| --- | --- | --- |");
  for (const r of detected) {
    lines.push(resultRow(r));
  }
  lines.push("");

  lines.push("## Health Score");
  lines.push("");
  lines.push(`| Metric | Score |`);
  lines.push(`| --- | --- |`);
  lines.push(`| Health | ${data.metrics.healthScore}/100 |`);
  lines.push(`| Complexity | ${data.metrics.complexityScore}/100 |`);
  lines.push(`| Maintainability | ${data.metrics.maintainabilityScore}/100 |`);
  lines.push(`| Maturity | ${data.metrics.maturityScore}/100 |`);
  lines.push(`| Production Readiness | ${data.metrics.productionReadiness}/100 |`);
  lines.push(`| Architecture | ${data.metrics.architectureScore}/100 |`);
  lines.push(`| Dependency Health | ${data.metrics.dependencyHealth}/100 |`);
  lines.push(`| Testing Coverage | ${data.metrics.testingCoverage}/100 |`);
  lines.push(`| Documentation | ${data.metrics.documentationScore}/100 |`);
  lines.push(`| Security | ${data.metrics.securityScore}/100 |`);
  lines.push(`| Performance | ${data.metrics.performanceScore}/100 |`);
  lines.push("");

  lines.push("## Recommendations");
  lines.push("");
  if (data.recommendations.length === 0) {
    lines.push("_No recommendations._");
  } else {
    for (const rec of data.recommendations) {
      lines.push(`### [${rec.severity.toUpperCase()}] ${rec.title}`);
      lines.push("");
      lines.push(`${rec.description}`);
      lines.push("");
      lines.push(`- **Category:** ${rec.category}`);
      lines.push(`- **Impact:** ${rec.impact}`);
      if (rec.fix) lines.push(`- **Fix:** ${rec.fix}`);
      lines.push("");
    }
  }

  lines.push("## Capabilities");
  lines.push("");
  if (data.capabilities.length === 0) {
    lines.push("_None detected._");
  } else {
    for (const cap of data.capabilities) {
      lines.push(`- ${cap}`);
    }
  }
  lines.push("");

  return lines.join("\n");
}
